version: 2
jobs:
  # Run Helm Lint checks
  helm-lint:
    working_directory: ~/stackstorm-ha
    docker:
      - image: lachlanevenson/k8s-helm
    steps:
      - checkout
      - run:
          name: Prepare Helm
          command: |
            set -x
            helm init --client-only
            helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
            helm dependency update
      - run:
          name: Helm Lint Check (Community)
          command: helm lint
      - run:
          name: Helm Lint Check (Enterprise)
          command: helm lint --set enterprise.enabled=true --set enterprise.license=123asd456fake
      - run:
          name: Helm template
          command: |
            mkdir -p enterprise community
            helm template --output-dir community .
            helm template --output-dir enterprise --set enterprise.enabled=true --set enterprise.license=123asd456fake .
      - persist_to_workspace:
          root: ~/stackstorm-ha/
          paths:
            - community
            - enterprise
            # TODO: Fill an issue in https://github.com/garethr/kubeval
            # 'charts' contains 3rd party templates which doesn't validate against schema due to minor 'object != null' API validation issues
            # See: https://circleci.com/gh/StackStorm/stackstorm-enterprise-ha/18
            #- charts

  # Run Kubernetes lint checks
  k8s-lint:
    docker:
      - image: garethr/kubeval
    steps:
      - attach_workspace:
          at: .
      - run:
          name: K8s Kubeval Lint Check (Community)
          command: kubeval $(find . -type f)
          working_directory: community/stackstorm-ha/templates/
      - run:
          name: K8s Kubeval Lint Check (Enterprise)
          command: kubeval $(find . -type f)
          working_directory: enterprise/stackstorm-ha/templates/

workflows:
  version: 2
  helm:
    jobs:
      - helm-lint
      - k8s-lint:
          requires:
            - helm-lint

experimental:
  notify:
    branches:
      only:
        - master
