---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-st2web
  annotations:
    description: SSL Certificate, used in nginx to serve StackStorm Web UI and services on HTTPS
  labels:
    app: st2web
    tier: frontend
    vendor: stackstorm
    support: {{ template "supportMethod" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  # SSL Certificate used for StackStorm Web UI in nginx (HTTPS)
  ssl_certificate: {{ required "A valid secret 'ssl_certificate' is required for st2web!" .Values.secrets.st2web.ssl_certificate | b64enc | quote }}
  # SSL Certificate private key used for StackStorm Web UI in nginx (HTTPS)
  ssl_certificate_key: {{ required "A valid secret 'ssl_certificate_key' is required for st2web!" .Values.secrets.st2web.ssl_certificate_key | b64enc | quote }}
